window.allsets= [
{setName:"NAQT British monarchs",termList:
	[
	{term:"Henry VIII",def:"The son of Tudor founder Henry VII. he brought England into both the Renaissance and the Reformation. -- patronized the philosopher Erasmus, the painter Hans Holbein the Younger, and the writer Thomas More. Originally a supporter of the Catholic Church--the Pope had named him \"Defender of the Faith\".he named himself head of the Church of England in 1533 so that he could divorce Catherine of Aragon and marry Anne Boleyn. -- executed top ministers who crossed him, including Thomas Cromwell and Thomas More. He married six times, but only his third wife, Jane Seymour, bore him a son, the sickly Edward VI."},
	{term:"Elizabeth I",def:"Known as the \"Virgin Queen\" because she never married, as Henry VIII's daughter by Anne Boleyn, the Catholic Church considered her illegitimate. After the death of her Catholic sister Mary I, -- tried to restore religious order by declaring England a Protestant state but naming herself only \"Governor\" of the Church. She foiled attempts at her throne by Spanish king Philip II and Mary, Queen of Scots; the latter -- reluctantly executed in 1587. Her reign saw great expansion of the English navy and the emergence of William Shakespeare. but when she died, the Crown went to Scottish king James VI, the son of Mary, Queen of Scots."},
	{term:"George III",def:"Though he lost the American colonies in the Revolutionary War, Britain's economic empire expanded during his reign. While --'s ministers kept their lives, they fell from power frequently, including both William Pitts, Lord Bute, and Lord North. Popular at home, he suffered from porphyria, causing the \"madness\" that ultimately led to the Regency period of his son."},
	{term:"Victoria",def:"The longest-reigning monarch in British history. she relinquished much of the remaining royal power, both to her husband Albert and to her favored prime ministers, Lord Melbourne, Robert Peel, and Benjamin Disraeli. After Albert's death in 1861, -- largely went into seclusion. she influenced the passage of the Reform Act of 1867, which doubled the number of Britons who could vote."},
	{term:"William I the Conqueror",def:"Duke of Normandy from 1035, he was promised succession to the throne by Edward the Confessor, but when Edward gave the throne to Harold II in 1066, -- invaded England, killing Harold and defeating the Anglo-Saxons at the Battle of Hastings. An able administrator, he authorized a survey of his kingdom in the 1086 Domesday Book. had replaced Anglo-Saxon nobles and clergy with Normans and other continentals."},
	{term:"Charles I",def:"The last absolute English monarch, -- ran into trouble almost immediately. His minister, the Duke of Buckingham, asked Parliament for money to fight costly foreign wars, and when Parliament balked, --- had to sign the Petition of Right. From 1630 to 1641 he tried to rule solo, but financial troubles forced him to call the Short and Long Parliaments. His attempt to reform the Scottish Church was the last straw, as Parliament entered into the English Civil War; they defeated --, convicting him of treason and executing him. England became a Commonwealth with Oliver Cromwell as Lord Protector."},
	{term:"James I",def:"At age one -- succeeded his mother Mary as King of Scotland. As the great-great-grandson of Henry VII, he claimed the English throne upon the death of Elizabeth I. -- was the intended target of Catholic fanatic Guy Fawkes' failed Gunpowder Plot in 1605. A believer in absolutism, -- dissolved Parliament from 1611 to 1621, favoring ministers Robert Cecil and the Duke of Buckingham instead. His rule saw English expansion into North America, through royal charter in Virginia and Puritan protest in Massachusetts."},
	{term:"Richard III",def:"He was made Duke of Gloucester in 1461 when his brother Edward IV deposed the Lancastrian king Henry VI, as part of the Wars of the Roses. Upon Edward's death in 1483, -- served as regent to his nephew Edward V, but likely had the boy murdered in the Tower of London that year. Two years later, -- died at the hands of Henry Tudor's Lancastrian forces at Bosworth Field, ending the Wars of the Roses and beginning the reign of Henry VII."},
	{term:"Elizabeth II",def:"Representative of the modern ceremonial monarchy, she and her husband \"Prince\" Philip Mountbatten have traveled the globe representing British interests. Marital failures by her sons Charles (the Prince of Wales) and Andrew have plagued her reign."},
	{term:"John Lackland",def:"Though he tried to seize the crown from his brother Richard while the latter was in Germany, Richard forgave -- and made him his successor. Excommunicated by the Pope for four years for refusing to accept Stephen Langton as Archbishop of Canterbury, -- was also weak as a fighter, as French King Philip II routed him at Bouvines in 1214. A year later, England's barons forced -- to sign the Magna Carta at Runnymede, an event that marked the beginning of the development of the British constitution."},
	{term:"Charles II",def:"While Cromwell ruled the Commonwealth, -- was crowned King of Scotland in 1651. After Cromwell died, -- used the Declaration of Breda to restore himself to the English throne. He fought two lackluster wars against the Dutch, and needed protection from Louis XIV through the Treaty of Dover. His wife Catherine of Braganza produced no legitimate heirs, but this \"Merry Monarch\" has as many as 14 illegitimate children. Tolerant of Catholics, he dissolved Parliament over the issue in 1681 and refused to prevent his brother James from succeeding him."},
	{term:"James II",def:"The 1678 Popish Plot against Charles II would have elevated the Roman Catholic -- to the throne, had it been real and not fabricated by Titus Oates. --'s three years, however, did feature heavy favoritism toward Catholics, so much so that Protestants invited --'s son-in-law William of Orange to rule England, deposing -- in the bloodless Glorious Revolution. Exiled to Louis XIV's court, he made an attempt to regain his crown in 1690 but was routed at the Battle of the Boyne."},
	{term:"Henry II",def:"The son of Geoffrey of Anjou and Matilda, he married Eleanor of Aquitaine in 1152, and invaded England the following year, forcing Stephen of Blois to acknowledge -- as his heir. While king he developed the common law and due process, but fought with Thomas Becket over submission to the Pope; -- had Becket executed in 1170 but performed penance at Canterbury. Eleanor and his four sons conspired with French king Philip II against -- on several occasions."},
	{term:"Richard I the Lion-Hearted",def:"Third son of Henry II, he spent only five months of his reign in England. He went on the Third Crusade to Jerusalem, winning many victories in the Holy Land, but on his way back was captured and ransomed by Holy Roman Emperor Henry VI. He also fought Philip II in Normandy, and died while defending his possessions in Aquitaine."},
	{term:"Alfred the Great",def:"Actually just the King of Wessex in southwestern England, he expelled the rival Danes from the Mercian town of London in 886, eventually conquering most of the Danelaw territory. -- also kept England from the worst of the Dark Ages by encouraging his bishops to foster literacy; in addition, he translated Boethius, Augustine, and the Venerable Bede's works into Anglo-Saxon."},
	]},
{setName:"NAQT French kings",termList:
	[
	{term:"Louis XIV",def:"--'s reign is often cited as the best historical example of an absolute monarchy. -- led France against most of the rest of Europe to win the throne of Spain for his grandson (the War of the Spanish Succession). He championed classical art, religious orthodoxy, and instituted a great program of building throughout France. Known as the \"Sun King,\" his 72-year-reign is the second longest in recorded history."},
	{term:"Louis XIII",def:"Sometimes working with his chief minister, Cardinal Richelieu, and sometimes against, -- turned France into the pre-eminent European power during his reign; this was largely achieved via French victories in the Thirty Years' War. The Three Musketeers is set in the early years of his reign."},
	{term:"Francis I",def:"Francis's early military victories (like the Battle of Marignano), his lavish court, and his support of luminaries like Leonardo da Vinci augured a splendid reign. His rivalry with Charles V of the Holy Roman Empire spelled his doom. He was captured in battle in 1525 and held for a humiliating ransom; wars continued after his release, but bankruptcy and religious strife laid France low."},
	{term:"Henry IV",def:"Founder of the house of Bourbon. --, the king of Navarre, became the heir to the throne when Henry III's brother died in 1584. After fighting Catholic opposition in the War of the Three Henries, he renounced Protestantism and accepted Catholicism in order to enter Paris and become king. With the help of Maximilien Sully he erased the national debt and removed much of the religious strife with the Edict of Nantes (1598)."},
	{term:"Philip II",def:"-- was the first of the great Capetian kings of France. Fighting and negotiating against Henry II, Richard I, and John of England, -- won back Normandy, Brittany, Anjou, and other territories. He also took part in the famous Third Crusade (with Richard I and Frederick Barbarossa) and made use of the Albigensian crusade to pave the way for the annexation of Languedoc by his successor."},
	{term:"Charles VIII",def:"--'s short reign is remarkable for the enormous cost in men and money of his Italian campaign but more so for the number of his successors that to followed his catastrophic lead. -- was motivated by a desire to govern Naples, which he had theoretically inherited. He died before he could surpass or absolve his disastrous first campaign with another."},
	{term:"Louis IX",def:"-- led the Seventh Crusade that ended in military disaster, but after his ransoming remained in the Holy Land to successfully negotiate for what he couldn't win. He returned to Europe with his reputation intact and negotiated a peace with England that saw Henry III become his vassal. He stabilized the French currency and is generally held to have reduced corruption in the kingdom. He died leading a crusade against Tunisia. Saint -- is the only canonized king of France."},
	{term:"Louis VIII",def:"Though he reigned for only three years, --'s contributions to the rise of French power were enormous. He annexed Languedoc and captured Poitou from England. He established the systems of appanages (land grants) which replaced the older, local nobles with barons who owed their fiefs to the crown; this allowed for the subsequent rise in French royal (and national) power."},
	{term:"Charles V",def:"-- had an inauspicious start (before his reign even began) with having to ransom his father, John II, from England for three million crowns and most of southwestern France. Later, with military advisor Bertrand du Guesclin, he recaptured almost all of that territory. He also concluded alliances with Portugal, Spain, and Flanders, reorganized the army, and restructured the collection of taxes while leading France's recovery from the devastation of the early period of the Hundred Years' War."},
	{term:"Henry III",def:"--'s reign was suffused with blood, at first because of the continuous Wars of Religion that pitted Catholics against Huguenots, but later because of the struggles that arose when it became clear that he was going to be the last of the Valois line. The War of the Three Henries broke out after his brother died and the then-Protestant Henry of Navarre (later Henry IV) became heir, leading the Catholic Holy League to strike out of fear for its interests. -- was assassinated by a crazed friar in 1589."},
	]},
];